config/routes.rb
Rails.application.routes.draw do
  get '/podcasts', to: 'podcasts#index', as: 'podcasts'
  post '/podcasts', to: 'podcasts#create'
  get '/podcasts/new', to: 'podcasts#new', as: 'new_podcast'
  get '/podcasts/:id', to: 'podcasts#show', as: 'podcast'
  puts '/podcasts/:id', to: 'podcasts#update'
  patch '/podcasts/:id', to: 'podcasts#update'
  get '/podcasts/:id/edit', to: 'podcasts#edit', as: 'edit_podcast'
  delete '/podcasts/:id', to: 'podcasts#delete'

  post '/podcasts/:id/episodes', to: 'episodes#create', as: 'create_episode'

  root to: 'podcasts#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/episode.rb
class Episode < ApplicationRecord
  validates :title, presence: true
  validates :show_notes, presence: true, length: { maximum: 100 }
  validates :mp3_file, presence: true, format: /\.mp3\Z/, on: :create
  validates :rating, presence: true

end

app/models/podcast.rb
class Podcast < ApplicationRecord
  validates :name, presence: true
  validates_uniqueness_of :name
  validates :genre, presence: true
  validates :image, presence: true, format: %r{\Ahttps?://}, on: :create

  has_many :episodes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  def create
    @podcast = Podcast.find(params[:id])
    @episode = @podcast.episodes.create(episode_params)

    redirect_to @podcast

  end

  private
  def episode_params
    params.permit(:title, :show_notes, :mp3_file, :rating)
  end
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  def index
    @podcasts = Podcast.all
  end

  def show
    @podcast = Podcast.find(params[:id])
  end

  def create
    @podcast = Podcast.new(podcast_params)

    @podcast.save ? (redirect_to @podcast) : (render 'new')
  end

  def new
    @podcast = Podcast.new
  end

  def update

  end

  def edit

  end

  def delete
    @podcast = Podcast.find(params[:id])

    Podcast.delete(@podcast)

    redirect_to podcasts_path
  end
  
  private
  def podcast_params
    params.permit(:name, :genre, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Podcasts</a>
  <ul class="navbar-nav mr-auto">
    <li class="nav-item"><a class="nav-link" href="<%= new_podcast_path %>">New Podcast</a></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PodcastApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar.html.erb' %>
    <%= yield %>
  </body>
</html>

app/views/podcasts/index.html.erb
<div class="jumbotron text-center">
  <h1 class="display-1">Podcasts</h1>
</div>

<div class="cards-container">
  <% @podcasts.each do |podcast| %>
    <div class="card border border-dark rounded">
      <img class="card-img-top" src="<%= podcast.image %>" alt="<%= podcast.name %> Image">
      <div class="card-body">
        <h3 class="card-title"><%= podcast.name %></h5>
        <h5 class="card-subtitle"><%= podcast.genre %></h5>
        <%= link_to "Show", podcast, class: "card-link btn btn-info" %>
      </div>
    </div>
  <% end %>
</div>

app/views/podcasts/new.html.erb
<h1>New Podcast</h1>

<form action="<%= podcasts_path %>" method="POST">
  <input type="hidden" value="<%= form_authenticity_token %>" name="authenticity_token" />

  <label for="name">Name</label>
  <input type="text" id="name" name="name" placeholder="e.g The Thinking Athiest" />

  <label for="genre">Genre</label>
  <input type="text" id="genre" name="genre" placeholder="e.g Politics" />

  <label for="image">Image Link</label>
  <input type="text" id="image" name="image" placeholder="e.g https://photos.com/image.jpg" />

  <input type="submit" value="Create" />
</form>

app/views/podcasts/show.html.erb
<div class="jumbotron text-center">
  <h1 class="display-1"><%= @podcast.name %></h1>
  <p class="lead"><%= @podcast.genre %></p>
</div>

<div class="image-container">
  <img src="<%= @podcast.image %>" alt="<%= @podcast.name %> Image">
</div>

<hr class="my-4">

<%= link_to "Delete", podcast_path(@podcast), method: :delete, class: "btn btn-danger" %>

<%# <table class="table"> %>
<%#   <thead> %>
<%#     <tr> %>
<%#       <th class="col"> </th> %>
<%#     </tr> %>
<%#   </thead> %>
<%# </table> %>

<h3>Episodes</h3>
<ul>
  <% @podcast.episodes.each do |episode| %>
    <li><%= episode.title %>
  <% end %>
</ul>

<h3>Create new episode</h3>

<form action="<%= create_episode_path %>" method="POST">
  <input type="hidden" value="<%= form_authenticity_token %>" name="authenticity_token" />

  <label for="title">Title</label>
  <input type="text" id="title" name="title" placeholder="e.g <%= Faker::Music.album %>" />

  <label for="show_notes">Show Notes</label>
  <input type="text" id="show_notes" name="show_notes" placeholder="e.g In this episode, <%= Faker::Name.first_name %>..." />

  <label for="mp3_file">MP3 File</label>
  <input type="text" id="mp3_file" name="mp3_file" placeholder="e.g /podcast/season1/episode1.mp3" />

  <label for="rating">Rating</label>
  <input type="range" id="rating" name="rating" min="0" max="10" value="5" oninput="rating_ouput.value = rating.value" />
  <output id="rating_ouput">5</output>

  <input type="submit" value="Create">
</form>

<%= link_to "Back", root_path %>